### PR TITLE
fix: display all layers in caption

### LINKED ISSUE #1820: Heatmaps appear in 'Manage layers' but not in the 'Browse data' tab.
**Describe the bug**
Any type of layer usually appears in the 'Browse data' tab. However, heatmaps are now excluded and can only be viewed in Edit mode via the 'Manage layers' tab. 

**To Reproduce**
1. Go to http://u.osmfr.org/m/1021391/
2. Click on 'See layers' and you'll find them missing as shown in the image below. 

**Screenshots**
Screenshot 2024-05-13 222750

### PR DESCRIPTION
**Pull request by yohanboniface**
And move caption in a dedicated module, as for browser, facets…

fix #1820

### CODE REVIEW

File: umap/static/umap/js/modules/caption.js [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+    DomUtil.element({
+      tagName: 'span',
+      parent: tilelayerCredit,
+      safeHTML: this.map.selected_tilelayer.getAttribution(),
+    })
+    const urls = {
+      leaflet: 'http://leafletjs.com',
+      django: 'https://www.djangoproject.com',
+      umap: 'http://wiki.openstreetmap.org/wiki/UMap',
+      changelog: 'https://umap-project.readthedocs.io/en/master/changelog/',
```
Comment (davidbgk) [inline umap/static/umap/js/modules/caption.js:93]:
```suggestion
      changelog: 'https://docs.umap-project.org/en/master/changelog/',
```

File: umap/static/umap/js/modules/caption.js [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+    this.addCredits(creditsContainer)
+    this.map.panel.open({ content: container })
+  }
+
+  addDataLayer(datalayer, container) {
+    if (!datalayer.options.inCaption) return
+    const p = DomUtil.create('p', 'datalayer-legend', container),
+      legend = DomUtil.create('span', '', p),
+      headline = DomUtil.create('strong', '', p)
+    datalayer.onceLoaded(function () {
```
Comment (davidbgk) [inline umap/static/umap/js/modules/caption.js:34]:
```suggestion
    datalayer.onceLoaded(() => {
```

File: umap/static/umap/js/umap.js [hunk 3]
```diff
@@ -916,6 +917,12 @@ U.Map = L.Map.extend({
     })
   },
 
+  openCaption: function () {
+    this.onceDatalayersLoaded(function () {
```
Comment (davidbgk) [inline umap/static/umap/js/umap.js:921]:
```suggestion
    this.onceDatalayersLoaded(this.caption.open.bind(this))
```
⚠️ requires to remove following lines.

**Review by davidbgk — APPROVED** [review]

File: umap/static/umap/js/umap.js (hunk 3 above)
Comment (davidbgk) [reply umap/static/umap/js/umap.js:921]: Looks better too 👍
