### PR TITLE
fix: allow to draw new proprotional circles and to drag them

### LINKED ISSUE #2171: Impossible to add a new marker on a "proportional circles" layer
**Describe the bug**

When adding a point on a "proportional circles" layer, an error is thrown in the console and the marker is not added.

**To Reproduce**

1. Create a new map
2. Add a few points
3. Convert the layer type to "proportional layers"
4. Add a new marker
5. Boom.

Here is the stack trace:

```JS
Uncaught TypeError: marker.enableEdit(...) is undefined
    startMarker Leaflet.Editable.js:339
    startMarker umap.js:1638
    addHooks umap.controls.js:110
    enable leaflet.toolbar.js:1
    enable leaflet.toolbar.js:1
    handler DomEvent.js:108
    addOne DomEvent.js:135
    on DomEvent.js:34
    _createIcon leaflet.toolbar.js:1
    appendToContainer leaflet.toolbar.js:1
    appendToContainer umap.controls.js:323
    redraw umap.controls.js:329
    fire Events.js:195
    set umap.js:96
    close panel.js:77
    handler DomEvent.js:108
    addOne DomEvent.js:135
    on DomEvent.js:34
    open panel.js:55
    edit layer.js:824
    callback layer.js:634
    onPostSync Leaflet.FormBuilder.js:116
    fire Events.js:195
    fireAndForward Leaflet.FormBuilder.js:140
    sync Leaflet.FormBuilder.js:169
    handler DomEvent.js:108
```

### PR DESCRIPTION
**Pull request by yohanboniface**
The main issue was because we overrided the `getLatLngs` function in our PointMixin class, so I changed the way feature get the latlngs from the UI classes. Plus getting CircleMarker to inherit more from Marker, through PointMixin.

fix #2171

### CODE REVIEW

File: umap/static/umap/js/modules/data/features.js [hunk 1]
```diff
@@ -607,6 +607,14 @@ export class Point extends Feature {
     }
   }
 
+  _getLatLngs() {
+    return this.ui.getLatLng()
+  }
+
+  _setLatLngs(latlng) {
+    this.ui.setLatLng(latlng)
```
Comment (davidbgk) [inline umap/static/umap/js/modules/data/features.js:615]: That one doesn't return the result of the operation, not sure if it's intentional?

File: umap/static/umap/js/modules/data/features.js [hunk 2]
```diff
@@ -678,6 +686,14 @@ class Path extends Feature {
     return !this.isEmpty()
   }
 
+  _getLatLngs() {
+    return this.ui.getLatLngs()
+  }
+
+  _setLatLngs(latlngs) {
+    return this.ui.setLatLngs(latlngs)
```
Comment (davidbgk) [inline umap/static/umap/js/modules/data/features.js:694]: What about that one then? 😛

Comment (yohanboniface) [reply umap/static/umap/js/modules/data/features.js:694]: Oops :p

**Review by davidbgk — APPROVED** [review]
