### PR TITLE
Use LANGUAGE_CODE instead of locale name for browser APIs

### LINKED ISSUE #1187: Locale "pt-pt" stoped working, need to use just "pt" for map to work
**Describe the bug**

Using URL's like https://umap.openstreetmap.fr/pt-pt/map/XXXXX stoped working correcty, to get the correct results the "pt-pt" needs to be replaced with just "pt"

**To Reproduce**
1. Go to https://umap.openstreetmap.fr/pt-pt/map/antenas-mobile-v21_724717
2. Only the pink layer will show data
3. Go to https://umap.openstreetmap.fr/pt/map/antenas-mobile-v21_724717
4. All layers will show data

**Expected behavior**
The URL with pt-pt should work as it always did

**Desktop:**
 - OS: Windows 10 or Ubuntu 20
 - Browser: Same issue with Firefox, Chrome or Brave
 - Version: any

**Smartphone (please complete the following information):**
 - Device: Any android device
 - OS: 12 or 13
 - Browser: stock or chrome
 - Version: any

**Additional context**

### PR DESCRIPTION
**Pull request by yohanboniface**
We use locale name (pt_PT) instead of the language code to use in localeCompare, which is wrong.

Given that both need to exist, let's also expose it in extendedProperties.

fix #1187

### CODE REVIEW

File: umap/static/umap/js/umap.js [hunk 1]
```diff
@@ -65,9 +65,16 @@ L.U.Map.include({
   ],
 
   initialize: function (el, geojson) {
-    if (geojson.properties && geojson.properties.locale)
```
Comment (davidbgk) [inline umap/static/umap/js/umap.js:68]: Not sure how critical it is but we are not testing anymore if `geojson` has `properties` first.

[Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) might be a way to handle the case without overcharging the syntax but it's for relatively recent browsers (2020).

**Review by davidbgk — APPROVED** [review]

File: umap/static/umap/js/umap.js (hunk 1 above)
Comment (yohanboniface) [reply umap/static/umap/js/umap.js:68]: Yep, I removed it be cause all the following lines were consuming properties without this check, so at this point…
